package tr.com.burakgul.multipleactivities;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;

public class AutoGeneratedActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        super.setContentView(R.layout.activity_auto_generated);
    }

    public void changeActivity(View view){
        Context applicationContext = super.getApplicationContext();
        Intent intent = new Intent(applicationContext,MainActivity.class);
        super.startActivity(intent);
    }
}