package tr.com.burakgul.multipleactivities;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

public class AutoGeneratedActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        super.setContentView(R.layout.activity_auto_generated);
    }
}