package tr.com.burakgul.multipleactivities;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

public class SecondActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        super.setContentView(R.layout.activity_second);
        Intent intent = super.getIntent();
        System.out.println(intent);
    }

    public void changeActivity(View view){
        Context activityContext = this;
        Context applicationContext = super.getApplicationContext();
        Intent autoGeneratedActivityIntent = new Intent(applicationContext,AutoGeneratedActivity.class);
        super.startActivity(autoGeneratedActivityIntent);
    }
}
